### ISSUE TITLE
ARM Linux binaries?

### ISSUE THREAD

**Issue by daniel-toman** [pomfort/mhl-tool#1]
Thank you for providing these open source tools! 

It appears your Linux binaries are built for the Ubuntu x64 environment. Any chance you would be able to provide binaries for Debian armhf architecture? 

I would like to run the MHL tool on the embedded ARM Debian Linux environment that's available on the [WD My Passport Wireless Pro](https://www.anandtech.com/show/10431/western-digital-my-passport-wireless-pro-wifi-hard-drive-review). Similar to the Gnarbox, Sanho UDMA, NEXTO DI etc. it has the ability to automatically copy the contents of an SD card to its internal hard drive, but it doesn't offer any file copy verification features. But it does allow [SSH login and installation of new Linux programs](https://scribblesandsnaps.com/2017/02/10/wd-my-passport-wireless-linux-hacks/), so it seems I could run my own MHL verifications with the right MHL tool binaries. Since I'm not that knowledgable about compiling Linux code for armhf I thought I would ask here first. 

Thank you!

**Comment by pomfort** [comment]
Hi Daniel,
I'm afraid we can't help you in that case, since we also don't have much experience cross compiling for other architectures and don't have a proper arm system handy to test, sorry.
Best, Alex
